// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package elasticsearch

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Manages an AWS Elasticsearch Domain.
//
// > This content is derived from https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/r/elasticsearch_domain.html.markdown.
type Domain struct {
	// URN is this resource's unique name assigned by Pulumi.
	URN pulumi.URNOutput `pulumi:"urn"`

	// ID is this resource's unique identifier assigned by its provider.
	ID pulumi.IDOutput `pulumi:"id"`

	// IAM policy document specifying the access policies for the domain
	AccessPolicies pulumi.StringOutput `pulumi:"accessPolicies"`

	// Key-value string pairs to specify advanced configuration options.
	// Note that the values for these configuration options must be strings (wrapped in quotes) or they
	// may be wrong and cause a perpetual diff, causing this provider to want to recreate your Elasticsearch
	// domain on every apply.
	AdvancedOptions pulumi.MapOutput `pulumi:"advancedOptions"`

	// Amazon Resource Name (ARN) of the domain.
	Arn pulumi.StringOutput `pulumi:"arn"`

	// Cluster configuration of the domain, see below.
	ClusterConfig pulumi.AnyOutput `pulumi:"clusterConfig"`

	CognitoOptions pulumi.AnyOutput `pulumi:"cognitoOptions"`

	// Unique identifier for the domain.
	DomainId pulumi.StringOutput `pulumi:"domainId"`

	// Name of the domain.
	DomainName pulumi.StringOutput `pulumi:"domainName"`

	// EBS related options, may be required based on chosen [instance size](https://aws.amazon.com/elasticsearch-service/pricing/). See below.
	EbsOptions pulumi.AnyOutput `pulumi:"ebsOptions"`

	// The version of Elasticsearch to deploy. Defaults to `1.5`
	ElasticsearchVersion pulumi.StringOutput `pulumi:"elasticsearchVersion"`

	// Encrypt at rest options. Only available for [certain instance types](http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-supported-instance-types.html). See below.
	EncryptAtRest pulumi.AnyOutput `pulumi:"encryptAtRest"`

	// Domain-specific endpoint used to submit index, search, and data upload requests.
	Endpoint pulumi.StringOutput `pulumi:"endpoint"`

	// Domain-specific endpoint for kibana without https scheme.
	// * `vpc_options.0.availability_zones` - If the domain was created inside a VPC, the names of the availability zones the configured `subnetIds` were created inside.
	// * `vpc_options.0.vpc_id` - If the domain was created inside a VPC, the ID of the VPC.
	KibanaEndpoint pulumi.StringOutput `pulumi:"kibanaEndpoint"`

	// Options for publishing slow logs to CloudWatch Logs.
	LogPublishingOptions pulumi.ArrayOutput `pulumi:"logPublishingOptions"`

	// Node-to-node encryption options. See below.
	NodeToNodeEncryption pulumi.AnyOutput `pulumi:"nodeToNodeEncryption"`

	// Snapshot related options, see below.
	SnapshotOptions pulumi.AnyOutput `pulumi:"snapshotOptions"`

	// A mapping of tags to assign to the resource
	Tags pulumi.MapOutput `pulumi:"tags"`

	// VPC related options, see below. Adding or removing this configuration forces a new resource ([documentation](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-vpc.html#es-vpc-limitations)).
	VpcOptions pulumi.AnyOutput `pulumi:"vpcOptions"`
}

// NewDomain registers a new resource with the given unique name, arguments, and options.
func NewDomain(ctx *pulumi.Context,
	name string, args *DomainArgs, opts ...pulumi.ResourceOpt) (*Domain, error) {
	inputs := map[string]pulumi.Input{}
	inputs["domainName"] = pulumi.Any()
	if args != nil {
		inputs["accessPolicies"] = args.AccessPolicies
		inputs["advancedOptions"] = args.AdvancedOptions
		inputs["clusterConfig"] = args.ClusterConfig
		inputs["cognitoOptions"] = args.CognitoOptions
		inputs["domainName"] = args.DomainName
		inputs["ebsOptions"] = args.EbsOptions
		inputs["elasticsearchVersion"] = args.ElasticsearchVersion
		inputs["encryptAtRest"] = args.EncryptAtRest
		inputs["logPublishingOptions"] = args.LogPublishingOptions
		inputs["nodeToNodeEncryption"] = args.NodeToNodeEncryption
		inputs["snapshotOptions"] = args.SnapshotOptions
		inputs["tags"] = args.Tags
		inputs["vpcOptions"] = args.VpcOptions
	}
	var resource Domain
	err := ctx.RegisterResource("aws:elasticsearch/domain:Domain", name, inputs, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDomain gets an existing Domain resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDomain(ctx *pulumi.Context,
	name string, id pulumi.ID, state *DomainState, opts ...pulumi.ResourceOpt) (*Domain, error) {
	inputs := map[string]pulumi.Input{}
	if state != nil {
		inputs["accessPolicies"] = state.AccessPolicies
		inputs["advancedOptions"] = state.AdvancedOptions
		inputs["arn"] = state.Arn
		inputs["clusterConfig"] = state.ClusterConfig
		inputs["cognitoOptions"] = state.CognitoOptions
		inputs["domainId"] = state.DomainId
		inputs["domainName"] = state.DomainName
		inputs["ebsOptions"] = state.EbsOptions
		inputs["elasticsearchVersion"] = state.ElasticsearchVersion
		inputs["encryptAtRest"] = state.EncryptAtRest
		inputs["endpoint"] = state.Endpoint
		inputs["kibanaEndpoint"] = state.KibanaEndpoint
		inputs["logPublishingOptions"] = state.LogPublishingOptions
		inputs["nodeToNodeEncryption"] = state.NodeToNodeEncryption
		inputs["snapshotOptions"] = state.SnapshotOptions
		inputs["tags"] = state.Tags
		inputs["vpcOptions"] = state.VpcOptions
	}
	var resource Domain
	err := ctx.ReadResource("aws:elasticsearch/domain:Domain", name, id, inputs, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetURN returns this resource's unique name assigned by Pulumi.
func (r *Domain) GetURN() pulumi.URNOutput {
	return r.URN
}

// GetID returns this resource's unique identifier assigned by its provider.
func (r *Domain) GetID() pulumi.IDOutput {
	return r.ID
}
// Input properties used for looking up and filtering Domain resources.
type DomainState struct {
	// IAM policy document specifying the access policies for the domain
	AccessPolicies pulumi.StringInput `pulumi:"accessPolicies"`
	// Key-value string pairs to specify advanced configuration options.
	// Note that the values for these configuration options must be strings (wrapped in quotes) or they
	// may be wrong and cause a perpetual diff, causing this provider to want to recreate your Elasticsearch
	// domain on every apply.
	AdvancedOptions pulumi.MapInput `pulumi:"advancedOptions"`
	// Amazon Resource Name (ARN) of the domain.
	Arn pulumi.StringInput `pulumi:"arn"`
	// Cluster configuration of the domain, see below.
	ClusterConfig pulumi.AnyInput `pulumi:"clusterConfig"`
	CognitoOptions pulumi.AnyInput `pulumi:"cognitoOptions"`
	// Unique identifier for the domain.
	DomainId pulumi.StringInput `pulumi:"domainId"`
	// Name of the domain.
	DomainName pulumi.StringInput `pulumi:"domainName"`
	// EBS related options, may be required based on chosen [instance size](https://aws.amazon.com/elasticsearch-service/pricing/). See below.
	EbsOptions pulumi.AnyInput `pulumi:"ebsOptions"`
	// The version of Elasticsearch to deploy. Defaults to `1.5`
	ElasticsearchVersion pulumi.StringInput `pulumi:"elasticsearchVersion"`
	// Encrypt at rest options. Only available for [certain instance types](http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-supported-instance-types.html). See below.
	EncryptAtRest pulumi.AnyInput `pulumi:"encryptAtRest"`
	// Domain-specific endpoint used to submit index, search, and data upload requests.
	Endpoint pulumi.StringInput `pulumi:"endpoint"`
	// Domain-specific endpoint for kibana without https scheme.
	// * `vpc_options.0.availability_zones` - If the domain was created inside a VPC, the names of the availability zones the configured `subnetIds` were created inside.
	// * `vpc_options.0.vpc_id` - If the domain was created inside a VPC, the ID of the VPC.
	KibanaEndpoint pulumi.StringInput `pulumi:"kibanaEndpoint"`
	// Options for publishing slow logs to CloudWatch Logs.
	LogPublishingOptions pulumi.ArrayInput `pulumi:"logPublishingOptions"`
	// Node-to-node encryption options. See below.
	NodeToNodeEncryption pulumi.AnyInput `pulumi:"nodeToNodeEncryption"`
	// Snapshot related options, see below.
	SnapshotOptions pulumi.AnyInput `pulumi:"snapshotOptions"`
	// A mapping of tags to assign to the resource
	Tags pulumi.MapInput `pulumi:"tags"`
	// VPC related options, see below. Adding or removing this configuration forces a new resource ([documentation](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-vpc.html#es-vpc-limitations)).
	VpcOptions pulumi.AnyInput `pulumi:"vpcOptions"`
}

// The set of arguments for constructing a Domain resource.
type DomainArgs struct {
	// IAM policy document specifying the access policies for the domain
	AccessPolicies pulumi.StringInput `pulumi:"accessPolicies"`
	// Key-value string pairs to specify advanced configuration options.
	// Note that the values for these configuration options must be strings (wrapped in quotes) or they
	// may be wrong and cause a perpetual diff, causing this provider to want to recreate your Elasticsearch
	// domain on every apply.
	AdvancedOptions pulumi.MapInput `pulumi:"advancedOptions"`
	// Cluster configuration of the domain, see below.
	ClusterConfig pulumi.AnyInput `pulumi:"clusterConfig"`
	CognitoOptions pulumi.AnyInput `pulumi:"cognitoOptions"`
	// Name of the domain.
	DomainName pulumi.StringInput `pulumi:"domainName"`
	// EBS related options, may be required based on chosen [instance size](https://aws.amazon.com/elasticsearch-service/pricing/). See below.
	EbsOptions pulumi.AnyInput `pulumi:"ebsOptions"`
	// The version of Elasticsearch to deploy. Defaults to `1.5`
	ElasticsearchVersion pulumi.StringInput `pulumi:"elasticsearchVersion"`
	// Encrypt at rest options. Only available for [certain instance types](http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-supported-instance-types.html). See below.
	EncryptAtRest pulumi.AnyInput `pulumi:"encryptAtRest"`
	// Options for publishing slow logs to CloudWatch Logs.
	LogPublishingOptions pulumi.ArrayInput `pulumi:"logPublishingOptions"`
	// Node-to-node encryption options. See below.
	NodeToNodeEncryption pulumi.AnyInput `pulumi:"nodeToNodeEncryption"`
	// Snapshot related options, see below.
	SnapshotOptions pulumi.AnyInput `pulumi:"snapshotOptions"`
	// A mapping of tags to assign to the resource
	Tags pulumi.MapInput `pulumi:"tags"`
	// VPC related options, see below. Adding or removing this configuration forces a new resource ([documentation](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-vpc.html#es-vpc-limitations)).
	VpcOptions pulumi.AnyInput `pulumi:"vpcOptions"`
}
