// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package sns

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Provides an SNS topic resource
// 
// ## Message Delivery Status Arguments
// 
// The `<endpoint>_success_feedback_role_arn` and `<endpoint>_failure_feedback_role_arn` arguments are used to give Amazon SNS write access to use CloudWatch Logs on your behalf. The `<endpoint>_success_feedback_sample_rate` argument is for specifying the sample rate percentage (0-100) of successfully delivered messages. After you configure the  `<endpoint>_failure_feedback_role_arn` argument, then all failed message deliveries generate CloudWatch Logs.
//
// > This content is derived from https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/r/sns_topic.html.markdown.
type Topic struct {
	// URN is this resource's unique name assigned by Pulumi.
	URN pulumi.URNOutput `pulumi:"urn"`

	// ID is this resource's unique identifier assigned by its provider.
	ID pulumi.IDOutput `pulumi:"id"`

	// IAM role for failure feedback
	ApplicationFailureFeedbackRoleArn pulumi.StringOutput `pulumi:"applicationFailureFeedbackRoleArn"`

	// The IAM role permitted to receive success feedback for this topic
	ApplicationSuccessFeedbackRoleArn pulumi.StringOutput `pulumi:"applicationSuccessFeedbackRoleArn"`

	// Percentage of success to sample
	ApplicationSuccessFeedbackSampleRate pulumi.IntOutput `pulumi:"applicationSuccessFeedbackSampleRate"`

	// The ARN of the SNS topic, as a more obvious property (clone of id)
	Arn pulumi.StringOutput `pulumi:"arn"`

	// The SNS delivery policy. More on [AWS documentation](https://docs.aws.amazon.com/sns/latest/dg/DeliveryPolicies.html)
	DeliveryPolicy pulumi.StringOutput `pulumi:"deliveryPolicy"`

	// The display name for the SNS topic
	DisplayName pulumi.StringOutput `pulumi:"displayName"`

	// IAM role for failure feedback
	HttpFailureFeedbackRoleArn pulumi.StringOutput `pulumi:"httpFailureFeedbackRoleArn"`

	// The IAM role permitted to receive success feedback for this topic
	HttpSuccessFeedbackRoleArn pulumi.StringOutput `pulumi:"httpSuccessFeedbackRoleArn"`

	// Percentage of success to sample
	HttpSuccessFeedbackSampleRate pulumi.IntOutput `pulumi:"httpSuccessFeedbackSampleRate"`

	// The ID of an AWS-managed customer master key (CMK) for Amazon SNS or a custom CMK. For more information, see [Key Terms](https://docs.aws.amazon.com/sns/latest/dg/sns-server-side-encryption.html#sse-key-terms)
	KmsMasterKeyId pulumi.StringOutput `pulumi:"kmsMasterKeyId"`

	// IAM role for failure feedback
	LambdaFailureFeedbackRoleArn pulumi.StringOutput `pulumi:"lambdaFailureFeedbackRoleArn"`

	// The IAM role permitted to receive success feedback for this topic
	LambdaSuccessFeedbackRoleArn pulumi.StringOutput `pulumi:"lambdaSuccessFeedbackRoleArn"`

	// Percentage of success to sample
	LambdaSuccessFeedbackSampleRate pulumi.IntOutput `pulumi:"lambdaSuccessFeedbackSampleRate"`

	// The friendly name for the SNS topic. By default generated by this provider.
	Name pulumi.StringOutput `pulumi:"name"`

	// The friendly name for the SNS topic. Conflicts with `name`.
	NamePrefix pulumi.StringOutput `pulumi:"namePrefix"`

	// The fully-formed AWS policy as JSON.
	Policy pulumi.StringOutput `pulumi:"policy"`

	// IAM role for failure feedback
	SqsFailureFeedbackRoleArn pulumi.StringOutput `pulumi:"sqsFailureFeedbackRoleArn"`

	// The IAM role permitted to receive success feedback for this topic
	SqsSuccessFeedbackRoleArn pulumi.StringOutput `pulumi:"sqsSuccessFeedbackRoleArn"`

	// Percentage of success to sample
	SqsSuccessFeedbackSampleRate pulumi.IntOutput `pulumi:"sqsSuccessFeedbackSampleRate"`

	// Key-value mapping of resource tags
	Tags pulumi.MapOutput `pulumi:"tags"`
}

// NewTopic registers a new resource with the given unique name, arguments, and options.
func NewTopic(ctx *pulumi.Context,
	name string, args *TopicArgs, opts ...pulumi.ResourceOpt) (*Topic, error) {
	inputs := map[string]pulumi.Input{}
	inputs["name"] = pulumi.Any()
	if args != nil {
		inputs["applicationFailureFeedbackRoleArn"] = args.ApplicationFailureFeedbackRoleArn
		inputs["applicationSuccessFeedbackRoleArn"] = args.ApplicationSuccessFeedbackRoleArn
		inputs["applicationSuccessFeedbackSampleRate"] = args.ApplicationSuccessFeedbackSampleRate
		inputs["deliveryPolicy"] = args.DeliveryPolicy
		inputs["displayName"] = args.DisplayName
		inputs["httpFailureFeedbackRoleArn"] = args.HttpFailureFeedbackRoleArn
		inputs["httpSuccessFeedbackRoleArn"] = args.HttpSuccessFeedbackRoleArn
		inputs["httpSuccessFeedbackSampleRate"] = args.HttpSuccessFeedbackSampleRate
		inputs["kmsMasterKeyId"] = args.KmsMasterKeyId
		inputs["lambdaFailureFeedbackRoleArn"] = args.LambdaFailureFeedbackRoleArn
		inputs["lambdaSuccessFeedbackRoleArn"] = args.LambdaSuccessFeedbackRoleArn
		inputs["lambdaSuccessFeedbackSampleRate"] = args.LambdaSuccessFeedbackSampleRate
		inputs["name"] = args.Name
		inputs["namePrefix"] = args.NamePrefix
		inputs["policy"] = args.Policy
		inputs["sqsFailureFeedbackRoleArn"] = args.SqsFailureFeedbackRoleArn
		inputs["sqsSuccessFeedbackRoleArn"] = args.SqsSuccessFeedbackRoleArn
		inputs["sqsSuccessFeedbackSampleRate"] = args.SqsSuccessFeedbackSampleRate
		inputs["tags"] = args.Tags
	}
	var resource Topic
	err := ctx.RegisterResource("aws:sns/topic:Topic", name, inputs, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTopic gets an existing Topic resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTopic(ctx *pulumi.Context,
	name string, id pulumi.ID, state *TopicState, opts ...pulumi.ResourceOpt) (*Topic, error) {
	inputs := map[string]pulumi.Input{}
	if state != nil {
		inputs["applicationFailureFeedbackRoleArn"] = state.ApplicationFailureFeedbackRoleArn
		inputs["applicationSuccessFeedbackRoleArn"] = state.ApplicationSuccessFeedbackRoleArn
		inputs["applicationSuccessFeedbackSampleRate"] = state.ApplicationSuccessFeedbackSampleRate
		inputs["arn"] = state.Arn
		inputs["deliveryPolicy"] = state.DeliveryPolicy
		inputs["displayName"] = state.DisplayName
		inputs["httpFailureFeedbackRoleArn"] = state.HttpFailureFeedbackRoleArn
		inputs["httpSuccessFeedbackRoleArn"] = state.HttpSuccessFeedbackRoleArn
		inputs["httpSuccessFeedbackSampleRate"] = state.HttpSuccessFeedbackSampleRate
		inputs["kmsMasterKeyId"] = state.KmsMasterKeyId
		inputs["lambdaFailureFeedbackRoleArn"] = state.LambdaFailureFeedbackRoleArn
		inputs["lambdaSuccessFeedbackRoleArn"] = state.LambdaSuccessFeedbackRoleArn
		inputs["lambdaSuccessFeedbackSampleRate"] = state.LambdaSuccessFeedbackSampleRate
		inputs["name"] = state.Name
		inputs["namePrefix"] = state.NamePrefix
		inputs["policy"] = state.Policy
		inputs["sqsFailureFeedbackRoleArn"] = state.SqsFailureFeedbackRoleArn
		inputs["sqsSuccessFeedbackRoleArn"] = state.SqsSuccessFeedbackRoleArn
		inputs["sqsSuccessFeedbackSampleRate"] = state.SqsSuccessFeedbackSampleRate
		inputs["tags"] = state.Tags
	}
	var resource Topic
	err := ctx.ReadResource("aws:sns/topic:Topic", name, id, inputs, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetURN returns this resource's unique name assigned by Pulumi.
func (r *Topic) GetURN() pulumi.URNOutput {
	return r.URN
}

// GetID returns this resource's unique identifier assigned by its provider.
func (r *Topic) GetID() pulumi.IDOutput {
	return r.ID
}
// Input properties used for looking up and filtering Topic resources.
type TopicState struct {
	// IAM role for failure feedback
	ApplicationFailureFeedbackRoleArn pulumi.StringInput `pulumi:"applicationFailureFeedbackRoleArn"`
	// The IAM role permitted to receive success feedback for this topic
	ApplicationSuccessFeedbackRoleArn pulumi.StringInput `pulumi:"applicationSuccessFeedbackRoleArn"`
	// Percentage of success to sample
	ApplicationSuccessFeedbackSampleRate pulumi.IntInput `pulumi:"applicationSuccessFeedbackSampleRate"`
	// The ARN of the SNS topic, as a more obvious property (clone of id)
	Arn pulumi.StringInput `pulumi:"arn"`
	// The SNS delivery policy. More on [AWS documentation](https://docs.aws.amazon.com/sns/latest/dg/DeliveryPolicies.html)
	DeliveryPolicy pulumi.StringInput `pulumi:"deliveryPolicy"`
	// The display name for the SNS topic
	DisplayName pulumi.StringInput `pulumi:"displayName"`
	// IAM role for failure feedback
	HttpFailureFeedbackRoleArn pulumi.StringInput `pulumi:"httpFailureFeedbackRoleArn"`
	// The IAM role permitted to receive success feedback for this topic
	HttpSuccessFeedbackRoleArn pulumi.StringInput `pulumi:"httpSuccessFeedbackRoleArn"`
	// Percentage of success to sample
	HttpSuccessFeedbackSampleRate pulumi.IntInput `pulumi:"httpSuccessFeedbackSampleRate"`
	// The ID of an AWS-managed customer master key (CMK) for Amazon SNS or a custom CMK. For more information, see [Key Terms](https://docs.aws.amazon.com/sns/latest/dg/sns-server-side-encryption.html#sse-key-terms)
	KmsMasterKeyId pulumi.StringInput `pulumi:"kmsMasterKeyId"`
	// IAM role for failure feedback
	LambdaFailureFeedbackRoleArn pulumi.StringInput `pulumi:"lambdaFailureFeedbackRoleArn"`
	// The IAM role permitted to receive success feedback for this topic
	LambdaSuccessFeedbackRoleArn pulumi.StringInput `pulumi:"lambdaSuccessFeedbackRoleArn"`
	// Percentage of success to sample
	LambdaSuccessFeedbackSampleRate pulumi.IntInput `pulumi:"lambdaSuccessFeedbackSampleRate"`
	// The friendly name for the SNS topic. By default generated by this provider.
	Name pulumi.StringInput `pulumi:"name"`
	// The friendly name for the SNS topic. Conflicts with `name`.
	NamePrefix pulumi.StringInput `pulumi:"namePrefix"`
	// The fully-formed AWS policy as JSON.
	Policy pulumi.StringInput `pulumi:"policy"`
	// IAM role for failure feedback
	SqsFailureFeedbackRoleArn pulumi.StringInput `pulumi:"sqsFailureFeedbackRoleArn"`
	// The IAM role permitted to receive success feedback for this topic
	SqsSuccessFeedbackRoleArn pulumi.StringInput `pulumi:"sqsSuccessFeedbackRoleArn"`
	// Percentage of success to sample
	SqsSuccessFeedbackSampleRate pulumi.IntInput `pulumi:"sqsSuccessFeedbackSampleRate"`
	// Key-value mapping of resource tags
	Tags pulumi.MapInput `pulumi:"tags"`
}

// The set of arguments for constructing a Topic resource.
type TopicArgs struct {
	// IAM role for failure feedback
	ApplicationFailureFeedbackRoleArn pulumi.StringInput `pulumi:"applicationFailureFeedbackRoleArn"`
	// The IAM role permitted to receive success feedback for this topic
	ApplicationSuccessFeedbackRoleArn pulumi.StringInput `pulumi:"applicationSuccessFeedbackRoleArn"`
	// Percentage of success to sample
	ApplicationSuccessFeedbackSampleRate pulumi.IntInput `pulumi:"applicationSuccessFeedbackSampleRate"`
	// The SNS delivery policy. More on [AWS documentation](https://docs.aws.amazon.com/sns/latest/dg/DeliveryPolicies.html)
	DeliveryPolicy pulumi.StringInput `pulumi:"deliveryPolicy"`
	// The display name for the SNS topic
	DisplayName pulumi.StringInput `pulumi:"displayName"`
	// IAM role for failure feedback
	HttpFailureFeedbackRoleArn pulumi.StringInput `pulumi:"httpFailureFeedbackRoleArn"`
	// The IAM role permitted to receive success feedback for this topic
	HttpSuccessFeedbackRoleArn pulumi.StringInput `pulumi:"httpSuccessFeedbackRoleArn"`
	// Percentage of success to sample
	HttpSuccessFeedbackSampleRate pulumi.IntInput `pulumi:"httpSuccessFeedbackSampleRate"`
	// The ID of an AWS-managed customer master key (CMK) for Amazon SNS or a custom CMK. For more information, see [Key Terms](https://docs.aws.amazon.com/sns/latest/dg/sns-server-side-encryption.html#sse-key-terms)
	KmsMasterKeyId pulumi.StringInput `pulumi:"kmsMasterKeyId"`
	// IAM role for failure feedback
	LambdaFailureFeedbackRoleArn pulumi.StringInput `pulumi:"lambdaFailureFeedbackRoleArn"`
	// The IAM role permitted to receive success feedback for this topic
	LambdaSuccessFeedbackRoleArn pulumi.StringInput `pulumi:"lambdaSuccessFeedbackRoleArn"`
	// Percentage of success to sample
	LambdaSuccessFeedbackSampleRate pulumi.IntInput `pulumi:"lambdaSuccessFeedbackSampleRate"`
	// The friendly name for the SNS topic. By default generated by this provider.
	Name pulumi.StringInput `pulumi:"name"`
	// The friendly name for the SNS topic. Conflicts with `name`.
	NamePrefix pulumi.StringInput `pulumi:"namePrefix"`
	// The fully-formed AWS policy as JSON.
	Policy pulumi.StringInput `pulumi:"policy"`
	// IAM role for failure feedback
	SqsFailureFeedbackRoleArn pulumi.StringInput `pulumi:"sqsFailureFeedbackRoleArn"`
	// The IAM role permitted to receive success feedback for this topic
	SqsSuccessFeedbackRoleArn pulumi.StringInput `pulumi:"sqsSuccessFeedbackRoleArn"`
	// Percentage of success to sample
	SqsSuccessFeedbackSampleRate pulumi.IntInput `pulumi:"sqsSuccessFeedbackSampleRate"`
	// Key-value mapping of resource tags
	Tags pulumi.MapInput `pulumi:"tags"`
}
