// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package xray

import (
	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Creates and manages an AWS XRay Sampling Rule.
//
// > This content is derived from https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/r/xray_sampling_rule.html.markdown.
type SamplingRule struct {
	// URN is this resource's unique name assigned by Pulumi.
	URN pulumi.URNOutput `pulumi:"urn"`

	// ID is this resource's unique identifier assigned by its provider.
	ID pulumi.IDOutput `pulumi:"id"`

	// The ARN of the sampling rule.
	Arn pulumi.StringOutput `pulumi:"arn"`

	// Matches attributes derived from the request.
	Attributes pulumi.MapOutput `pulumi:"attributes"`

	// The percentage of matching requests to instrument, after the reservoir is exhausted.
	FixedRate pulumi.Float64Output `pulumi:"fixedRate"`

	// Matches the hostname from a request URL.
	Host pulumi.StringOutput `pulumi:"host"`

	// Matches the HTTP method of a request.
	HttpMethod pulumi.StringOutput `pulumi:"httpMethod"`

	// The priority of the sampling rule.
	Priority pulumi.IntOutput `pulumi:"priority"`

	// A fixed number of matching requests to instrument per second, prior to applying the fixed rate. The reservoir is not used directly by services, but applies to all services using the rule collectively.
	ReservoirSize pulumi.IntOutput `pulumi:"reservoirSize"`

	// Matches the ARN of the AWS resource on which the service runs.
	ResourceArn pulumi.StringOutput `pulumi:"resourceArn"`

	// The name of the sampling rule.
	RuleName pulumi.StringOutput `pulumi:"ruleName"`

	// Matches the `name` that the service uses to identify itself in segments.
	ServiceName pulumi.StringOutput `pulumi:"serviceName"`

	// Matches the `origin` that the service uses to identify its type in segments.
	ServiceType pulumi.StringOutput `pulumi:"serviceType"`

	// Matches the path from a request URL.
	UrlPath pulumi.StringOutput `pulumi:"urlPath"`

	// The version of the sampling rule format (`1` )
	Version pulumi.IntOutput `pulumi:"version"`
}

// NewSamplingRule registers a new resource with the given unique name, arguments, and options.
func NewSamplingRule(ctx *pulumi.Context,
	name string, args *SamplingRuleArgs, opts ...pulumi.ResourceOpt) (*SamplingRule, error) {
	if args == nil || args.FixedRate == nil {
		return nil, errors.New("missing required argument 'FixedRate'")
	}
	if args == nil || args.Host == nil {
		return nil, errors.New("missing required argument 'Host'")
	}
	if args == nil || args.HttpMethod == nil {
		return nil, errors.New("missing required argument 'HttpMethod'")
	}
	if args == nil || args.Priority == nil {
		return nil, errors.New("missing required argument 'Priority'")
	}
	if args == nil || args.ReservoirSize == nil {
		return nil, errors.New("missing required argument 'ReservoirSize'")
	}
	if args == nil || args.ResourceArn == nil {
		return nil, errors.New("missing required argument 'ResourceArn'")
	}
	if args == nil || args.ServiceName == nil {
		return nil, errors.New("missing required argument 'ServiceName'")
	}
	if args == nil || args.ServiceType == nil {
		return nil, errors.New("missing required argument 'ServiceType'")
	}
	if args == nil || args.UrlPath == nil {
		return nil, errors.New("missing required argument 'UrlPath'")
	}
	if args == nil || args.Version == nil {
		return nil, errors.New("missing required argument 'Version'")
	}
	inputs := map[string]pulumi.Input{}
	if args != nil {
		inputs["attributes"] = args.Attributes
		inputs["fixedRate"] = args.FixedRate
		inputs["host"] = args.Host
		inputs["httpMethod"] = args.HttpMethod
		inputs["priority"] = args.Priority
		inputs["reservoirSize"] = args.ReservoirSize
		inputs["resourceArn"] = args.ResourceArn
		inputs["ruleName"] = args.RuleName
		inputs["serviceName"] = args.ServiceName
		inputs["serviceType"] = args.ServiceType
		inputs["urlPath"] = args.UrlPath
		inputs["version"] = args.Version
	}
	var resource SamplingRule
	err := ctx.RegisterResource("aws:xray/samplingRule:SamplingRule", name, inputs, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSamplingRule gets an existing SamplingRule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSamplingRule(ctx *pulumi.Context,
	name string, id pulumi.ID, state *SamplingRuleState, opts ...pulumi.ResourceOpt) (*SamplingRule, error) {
	inputs := map[string]pulumi.Input{}
	if state != nil {
		inputs["arn"] = state.Arn
		inputs["attributes"] = state.Attributes
		inputs["fixedRate"] = state.FixedRate
		inputs["host"] = state.Host
		inputs["httpMethod"] = state.HttpMethod
		inputs["priority"] = state.Priority
		inputs["reservoirSize"] = state.ReservoirSize
		inputs["resourceArn"] = state.ResourceArn
		inputs["ruleName"] = state.RuleName
		inputs["serviceName"] = state.ServiceName
		inputs["serviceType"] = state.ServiceType
		inputs["urlPath"] = state.UrlPath
		inputs["version"] = state.Version
	}
	var resource SamplingRule
	err := ctx.ReadResource("aws:xray/samplingRule:SamplingRule", name, id, inputs, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetURN returns this resource's unique name assigned by Pulumi.
func (r *SamplingRule) GetURN() pulumi.URNOutput {
	return r.URN
}

// GetID returns this resource's unique identifier assigned by its provider.
func (r *SamplingRule) GetID() pulumi.IDOutput {
	return r.ID
}
// Input properties used for looking up and filtering SamplingRule resources.
type SamplingRuleState struct {
	// The ARN of the sampling rule.
	Arn pulumi.StringInput `pulumi:"arn"`
	// Matches attributes derived from the request.
	Attributes pulumi.MapInput `pulumi:"attributes"`
	// The percentage of matching requests to instrument, after the reservoir is exhausted.
	FixedRate pulumi.Float64Input `pulumi:"fixedRate"`
	// Matches the hostname from a request URL.
	Host pulumi.StringInput `pulumi:"host"`
	// Matches the HTTP method of a request.
	HttpMethod pulumi.StringInput `pulumi:"httpMethod"`
	// The priority of the sampling rule.
	Priority pulumi.IntInput `pulumi:"priority"`
	// A fixed number of matching requests to instrument per second, prior to applying the fixed rate. The reservoir is not used directly by services, but applies to all services using the rule collectively.
	ReservoirSize pulumi.IntInput `pulumi:"reservoirSize"`
	// Matches the ARN of the AWS resource on which the service runs.
	ResourceArn pulumi.StringInput `pulumi:"resourceArn"`
	// The name of the sampling rule.
	RuleName pulumi.StringInput `pulumi:"ruleName"`
	// Matches the `name` that the service uses to identify itself in segments.
	ServiceName pulumi.StringInput `pulumi:"serviceName"`
	// Matches the `origin` that the service uses to identify its type in segments.
	ServiceType pulumi.StringInput `pulumi:"serviceType"`
	// Matches the path from a request URL.
	UrlPath pulumi.StringInput `pulumi:"urlPath"`
	// The version of the sampling rule format (`1` )
	Version pulumi.IntInput `pulumi:"version"`
}

// The set of arguments for constructing a SamplingRule resource.
type SamplingRuleArgs struct {
	// Matches attributes derived from the request.
	Attributes pulumi.MapInput `pulumi:"attributes"`
	// The percentage of matching requests to instrument, after the reservoir is exhausted.
	FixedRate pulumi.Float64Input `pulumi:"fixedRate"`
	// Matches the hostname from a request URL.
	Host pulumi.StringInput `pulumi:"host"`
	// Matches the HTTP method of a request.
	HttpMethod pulumi.StringInput `pulumi:"httpMethod"`
	// The priority of the sampling rule.
	Priority pulumi.IntInput `pulumi:"priority"`
	// A fixed number of matching requests to instrument per second, prior to applying the fixed rate. The reservoir is not used directly by services, but applies to all services using the rule collectively.
	ReservoirSize pulumi.IntInput `pulumi:"reservoirSize"`
	// Matches the ARN of the AWS resource on which the service runs.
	ResourceArn pulumi.StringInput `pulumi:"resourceArn"`
	// The name of the sampling rule.
	RuleName pulumi.StringInput `pulumi:"ruleName"`
	// Matches the `name` that the service uses to identify itself in segments.
	ServiceName pulumi.StringInput `pulumi:"serviceName"`
	// Matches the `origin` that the service uses to identify its type in segments.
	ServiceType pulumi.StringInput `pulumi:"serviceType"`
	// Matches the path from a request URL.
	UrlPath pulumi.StringInput `pulumi:"urlPath"`
	// The version of the sampling rule format (`1` )
	Version pulumi.IntInput `pulumi:"version"`
}
