// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ec2

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Provides information about a Launch Template.
//
// > This content is derived from https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/d/launch_template.html.markdown.
func LookupLaunchTemplate(ctx *pulumi.Context, args *GetLaunchTemplateArgs) (*GetLaunchTemplateResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["name"] = args.Name
		inputs["tags"] = args.Tags
	}
	outputs, err := ctx.Invoke("aws:ec2/getLaunchTemplate:getLaunchTemplate", inputs)
	if err != nil {
		return nil, err
	}
	return &GetLaunchTemplateResult{
		Arn: outputs["arn"],
		BlockDeviceMappings: outputs["blockDeviceMappings"],
		CreditSpecifications: outputs["creditSpecifications"],
		DefaultVersion: outputs["defaultVersion"],
		Description: outputs["description"],
		DisableApiTermination: outputs["disableApiTermination"],
		EbsOptimized: outputs["ebsOptimized"],
		ElasticGpuSpecifications: outputs["elasticGpuSpecifications"],
		IamInstanceProfiles: outputs["iamInstanceProfiles"],
		ImageId: outputs["imageId"],
		InstanceInitiatedShutdownBehavior: outputs["instanceInitiatedShutdownBehavior"],
		InstanceMarketOptions: outputs["instanceMarketOptions"],
		InstanceType: outputs["instanceType"],
		KernelId: outputs["kernelId"],
		KeyName: outputs["keyName"],
		LatestVersion: outputs["latestVersion"],
		Monitorings: outputs["monitorings"],
		Name: outputs["name"],
		NetworkInterfaces: outputs["networkInterfaces"],
		Placements: outputs["placements"],
		RamDiskId: outputs["ramDiskId"],
		SecurityGroupNames: outputs["securityGroupNames"],
		TagSpecifications: outputs["tagSpecifications"],
		Tags: outputs["tags"],
		UserData: outputs["userData"],
		VpcSecurityGroupIds: outputs["vpcSecurityGroupIds"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getLaunchTemplate.
type GetLaunchTemplateArgs struct {
	// The name of the launch template.
	Name pulumi.StringInput `pulumi:"name"`
	Tags pulumi.MapInput `pulumi:"tags"`
}

// A collection of values returned by getLaunchTemplate.
type GetLaunchTemplateResult struct {
	// Amazon Resource Name (ARN) of the launch template.
	Arn string `pulumi:"arn"`
	// Specify volumes to attach to the instance besides the volumes specified by the AMI.
	BlockDeviceMappings []interface{} `pulumi:"blockDeviceMappings"`
	// Customize the credit specification of the instance. See Credit
	// Specification below for more details.
	CreditSpecifications []interface{} `pulumi:"creditSpecifications"`
	// The default version of the launch template.
	DefaultVersion int `pulumi:"defaultVersion"`
	// Description of the launch template.
	Description string `pulumi:"description"`
	// If `true`, enables [EC2 Instance
	// Termination Protection](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/terminating-instances.html#Using_ChangingDisableAPITermination)
	DisableApiTermination bool `pulumi:"disableApiTermination"`
	// If `true`, the launched EC2 instance will be EBS-optimized.
	EbsOptimized string `pulumi:"ebsOptimized"`
	// The elastic GPU to attach to the instance. See Elastic GPU
	// below for more details.
	ElasticGpuSpecifications []interface{} `pulumi:"elasticGpuSpecifications"`
	// The IAM Instance Profile to launch the instance with. See Instance Profile
	// below for more details.
	IamInstanceProfiles []interface{} `pulumi:"iamInstanceProfiles"`
	// The AMI from which to launch the instance.
	ImageId string `pulumi:"imageId"`
	// Shutdown behavior for the instance. Can be `stop` or `terminate`.
	// (Default: `stop`).
	InstanceInitiatedShutdownBehavior string `pulumi:"instanceInitiatedShutdownBehavior"`
	// The market (purchasing) option for the instance.
	// below for details.
	InstanceMarketOptions []interface{} `pulumi:"instanceMarketOptions"`
	// The type of the instance.
	InstanceType string `pulumi:"instanceType"`
	// The kernel ID.
	KernelId string `pulumi:"kernelId"`
	// The key name to use for the instance.
	KeyName string `pulumi:"keyName"`
	// The latest version of the launch template.
	LatestVersion int `pulumi:"latestVersion"`
	// The monitoring option for the instance.
	Monitorings []interface{} `pulumi:"monitorings"`
	Name string `pulumi:"name"`
	// Customize network interfaces to be attached at instance boot time. See Network
	// Interfaces below for more details.
	NetworkInterfaces []interface{} `pulumi:"networkInterfaces"`
	// The placement of the instance.
	Placements []interface{} `pulumi:"placements"`
	// The ID of the RAM disk.
	RamDiskId string `pulumi:"ramDiskId"`
	// A list of security group names to associate with. If you are creating Instances in a VPC, use
	// `vpcSecurityGroupIds` instead.
	SecurityGroupNames []interface{} `pulumi:"securityGroupNames"`
	// The tags to apply to the resources during launch.
	TagSpecifications []interface{} `pulumi:"tagSpecifications"`
	// (Optional) A mapping of tags to assign to the launch template.
	Tags map[string]interface{} `pulumi:"tags"`
	// The Base64-encoded user data to provide when launching the instance.
	UserData string `pulumi:"userData"`
	// A list of security group IDs to associate with.
	VpcSecurityGroupIds []interface{} `pulumi:"vpcSecurityGroupIds"`
	// id is the provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
}
