// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package servicequotas

import (
	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Manages an individual Service Quota.
//
// > This content is derived from https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/r/servicequotas_service_quota.html.markdown.
type ServiceQuota struct {
	// URN is this resource's unique name assigned by Pulumi.
	URN pulumi.URNOutput `pulumi:"urn"`

	// ID is this resource's unique identifier assigned by its provider.
	ID pulumi.IDOutput `pulumi:"id"`

	// Whether the service quota can be increased.
	Adjustable pulumi.BoolOutput `pulumi:"adjustable"`

	// Amazon Resource Name (ARN) of the service quota.
	Arn pulumi.StringOutput `pulumi:"arn"`

	// Default value of the service quota.
	DefaultValue pulumi.Float64Output `pulumi:"defaultValue"`

	// Code of the service quota to track. For example: `L-F678F1CE`. Available values can be found with the [AWS CLI service-quotas list-service-quotas command](https://docs.aws.amazon.com/cli/latest/reference/service-quotas/list-service-quotas.html).
	QuotaCode pulumi.StringOutput `pulumi:"quotaCode"`

	// Name of the quota.
	QuotaName pulumi.StringOutput `pulumi:"quotaName"`

	RequestId pulumi.StringOutput `pulumi:"requestId"`

	RequestStatus pulumi.StringOutput `pulumi:"requestStatus"`

	// Code of the service to track. For example: `vpc`. Available values can be found with the [AWS CLI service-quotas list-services command](https://docs.aws.amazon.com/cli/latest/reference/service-quotas/list-services.html).
	ServiceCode pulumi.StringOutput `pulumi:"serviceCode"`

	// Name of the service.
	ServiceName pulumi.StringOutput `pulumi:"serviceName"`

	// Float specifying the desired value for the service quota. If the desired value is higher than the current value, a quota increase request is submitted. When a known request is submitted and pending, the value reflects the desired value of the pending request.
	Value pulumi.Float64Output `pulumi:"value"`
}

// NewServiceQuota registers a new resource with the given unique name, arguments, and options.
func NewServiceQuota(ctx *pulumi.Context,
	name string, args *ServiceQuotaArgs, opts ...pulumi.ResourceOpt) (*ServiceQuota, error) {
	if args == nil || args.QuotaCode == nil {
		return nil, errors.New("missing required argument 'QuotaCode'")
	}
	if args == nil || args.ServiceCode == nil {
		return nil, errors.New("missing required argument 'ServiceCode'")
	}
	if args == nil || args.Value == nil {
		return nil, errors.New("missing required argument 'Value'")
	}
	inputs := map[string]pulumi.Input{}
	if args != nil {
		inputs["quotaCode"] = args.QuotaCode
		inputs["serviceCode"] = args.ServiceCode
		inputs["value"] = args.Value
	}
	var resource ServiceQuota
	err := ctx.RegisterResource("aws:servicequotas/serviceQuota:ServiceQuota", name, inputs, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetServiceQuota gets an existing ServiceQuota resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetServiceQuota(ctx *pulumi.Context,
	name string, id pulumi.ID, state *ServiceQuotaState, opts ...pulumi.ResourceOpt) (*ServiceQuota, error) {
	inputs := map[string]pulumi.Input{}
	if state != nil {
		inputs["adjustable"] = state.Adjustable
		inputs["arn"] = state.Arn
		inputs["defaultValue"] = state.DefaultValue
		inputs["quotaCode"] = state.QuotaCode
		inputs["quotaName"] = state.QuotaName
		inputs["requestId"] = state.RequestId
		inputs["requestStatus"] = state.RequestStatus
		inputs["serviceCode"] = state.ServiceCode
		inputs["serviceName"] = state.ServiceName
		inputs["value"] = state.Value
	}
	var resource ServiceQuota
	err := ctx.ReadResource("aws:servicequotas/serviceQuota:ServiceQuota", name, id, inputs, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetURN returns this resource's unique name assigned by Pulumi.
func (r *ServiceQuota) GetURN() pulumi.URNOutput {
	return r.URN
}

// GetID returns this resource's unique identifier assigned by its provider.
func (r *ServiceQuota) GetID() pulumi.IDOutput {
	return r.ID
}
// Input properties used for looking up and filtering ServiceQuota resources.
type ServiceQuotaState struct {
	// Whether the service quota can be increased.
	Adjustable pulumi.BoolInput `pulumi:"adjustable"`
	// Amazon Resource Name (ARN) of the service quota.
	Arn pulumi.StringInput `pulumi:"arn"`
	// Default value of the service quota.
	DefaultValue pulumi.Float64Input `pulumi:"defaultValue"`
	// Code of the service quota to track. For example: `L-F678F1CE`. Available values can be found with the [AWS CLI service-quotas list-service-quotas command](https://docs.aws.amazon.com/cli/latest/reference/service-quotas/list-service-quotas.html).
	QuotaCode pulumi.StringInput `pulumi:"quotaCode"`
	// Name of the quota.
	QuotaName pulumi.StringInput `pulumi:"quotaName"`
	RequestId pulumi.StringInput `pulumi:"requestId"`
	RequestStatus pulumi.StringInput `pulumi:"requestStatus"`
	// Code of the service to track. For example: `vpc`. Available values can be found with the [AWS CLI service-quotas list-services command](https://docs.aws.amazon.com/cli/latest/reference/service-quotas/list-services.html).
	ServiceCode pulumi.StringInput `pulumi:"serviceCode"`
	// Name of the service.
	ServiceName pulumi.StringInput `pulumi:"serviceName"`
	// Float specifying the desired value for the service quota. If the desired value is higher than the current value, a quota increase request is submitted. When a known request is submitted and pending, the value reflects the desired value of the pending request.
	Value pulumi.Float64Input `pulumi:"value"`
}

// The set of arguments for constructing a ServiceQuota resource.
type ServiceQuotaArgs struct {
	// Code of the service quota to track. For example: `L-F678F1CE`. Available values can be found with the [AWS CLI service-quotas list-service-quotas command](https://docs.aws.amazon.com/cli/latest/reference/service-quotas/list-service-quotas.html).
	QuotaCode pulumi.StringInput `pulumi:"quotaCode"`
	// Code of the service to track. For example: `vpc`. Available values can be found with the [AWS CLI service-quotas list-services command](https://docs.aws.amazon.com/cli/latest/reference/service-quotas/list-services.html).
	ServiceCode pulumi.StringInput `pulumi:"serviceCode"`
	// Float specifying the desired value for the service quota. If the desired value is higher than the current value, a quota increase request is submitted. When a known request is submitted and pending, the value reflects the desired value of the pending request.
	Value pulumi.Float64Input `pulumi:"value"`
}
