// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ses

import (
	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Provides an SES receipt rule resource
//
// > This content is derived from https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/r/ses_receipt_rule.html.markdown.
type ReceiptRule struct {
	// URN is this resource's unique name assigned by Pulumi.
	URN pulumi.URNOutput `pulumi:"urn"`

	// ID is this resource's unique identifier assigned by its provider.
	ID pulumi.IDOutput `pulumi:"id"`

	// A list of Add Header Action blocks. Documented below.
	AddHeaderActions pulumi.ArrayOutput `pulumi:"addHeaderActions"`

	// The name of the rule to place this rule after
	After pulumi.StringOutput `pulumi:"after"`

	// A list of Bounce Action blocks. Documented below.
	BounceActions pulumi.ArrayOutput `pulumi:"bounceActions"`

	// If true, the rule will be enabled
	Enabled pulumi.BoolOutput `pulumi:"enabled"`

	// A list of Lambda Action blocks. Documented below.
	LambdaActions pulumi.ArrayOutput `pulumi:"lambdaActions"`

	// The name of the rule
	Name pulumi.StringOutput `pulumi:"name"`

	// A list of email addresses
	Recipients pulumi.ArrayOutput `pulumi:"recipients"`

	// The name of the rule set
	RuleSetName pulumi.StringOutput `pulumi:"ruleSetName"`

	// A list of S3 Action blocks. Documented below.
	S3Actions pulumi.ArrayOutput `pulumi:"s3Actions"`

	// If true, incoming emails will be scanned for spam and viruses
	ScanEnabled pulumi.BoolOutput `pulumi:"scanEnabled"`

	// A list of SNS Action blocks. Documented below.
	SnsActions pulumi.ArrayOutput `pulumi:"snsActions"`

	// A list of Stop Action blocks. Documented below.
	StopActions pulumi.ArrayOutput `pulumi:"stopActions"`

	// Require or Optional
	TlsPolicy pulumi.StringOutput `pulumi:"tlsPolicy"`

	// A list of WorkMail Action blocks. Documented below.
	WorkmailActions pulumi.ArrayOutput `pulumi:"workmailActions"`
}

// NewReceiptRule registers a new resource with the given unique name, arguments, and options.
func NewReceiptRule(ctx *pulumi.Context,
	name string, args *ReceiptRuleArgs, opts ...pulumi.ResourceOpt) (*ReceiptRule, error) {
	if args == nil || args.RuleSetName == nil {
		return nil, errors.New("missing required argument 'RuleSetName'")
	}
	inputs := map[string]pulumi.Input{}
	inputs["name"] = pulumi.Any()
	if args != nil {
		inputs["addHeaderActions"] = args.AddHeaderActions
		inputs["after"] = args.After
		inputs["bounceActions"] = args.BounceActions
		inputs["enabled"] = args.Enabled
		inputs["lambdaActions"] = args.LambdaActions
		inputs["name"] = args.Name
		inputs["recipients"] = args.Recipients
		inputs["ruleSetName"] = args.RuleSetName
		inputs["s3Actions"] = args.S3Actions
		inputs["scanEnabled"] = args.ScanEnabled
		inputs["snsActions"] = args.SnsActions
		inputs["stopActions"] = args.StopActions
		inputs["tlsPolicy"] = args.TlsPolicy
		inputs["workmailActions"] = args.WorkmailActions
	}
	var resource ReceiptRule
	err := ctx.RegisterResource("aws:ses/receiptRule:ReceiptRule", name, inputs, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetReceiptRule gets an existing ReceiptRule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetReceiptRule(ctx *pulumi.Context,
	name string, id pulumi.ID, state *ReceiptRuleState, opts ...pulumi.ResourceOpt) (*ReceiptRule, error) {
	inputs := map[string]pulumi.Input{}
	if state != nil {
		inputs["addHeaderActions"] = state.AddHeaderActions
		inputs["after"] = state.After
		inputs["bounceActions"] = state.BounceActions
		inputs["enabled"] = state.Enabled
		inputs["lambdaActions"] = state.LambdaActions
		inputs["name"] = state.Name
		inputs["recipients"] = state.Recipients
		inputs["ruleSetName"] = state.RuleSetName
		inputs["s3Actions"] = state.S3Actions
		inputs["scanEnabled"] = state.ScanEnabled
		inputs["snsActions"] = state.SnsActions
		inputs["stopActions"] = state.StopActions
		inputs["tlsPolicy"] = state.TlsPolicy
		inputs["workmailActions"] = state.WorkmailActions
	}
	var resource ReceiptRule
	err := ctx.ReadResource("aws:ses/receiptRule:ReceiptRule", name, id, inputs, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetURN returns this resource's unique name assigned by Pulumi.
func (r *ReceiptRule) GetURN() pulumi.URNOutput {
	return r.URN
}

// GetID returns this resource's unique identifier assigned by its provider.
func (r *ReceiptRule) GetID() pulumi.IDOutput {
	return r.ID
}
// Input properties used for looking up and filtering ReceiptRule resources.
type ReceiptRuleState struct {
	// A list of Add Header Action blocks. Documented below.
	AddHeaderActions pulumi.ArrayInput `pulumi:"addHeaderActions"`
	// The name of the rule to place this rule after
	After pulumi.StringInput `pulumi:"after"`
	// A list of Bounce Action blocks. Documented below.
	BounceActions pulumi.ArrayInput `pulumi:"bounceActions"`
	// If true, the rule will be enabled
	Enabled pulumi.BoolInput `pulumi:"enabled"`
	// A list of Lambda Action blocks. Documented below.
	LambdaActions pulumi.ArrayInput `pulumi:"lambdaActions"`
	// The name of the rule
	Name pulumi.StringInput `pulumi:"name"`
	// A list of email addresses
	Recipients pulumi.ArrayInput `pulumi:"recipients"`
	// The name of the rule set
	RuleSetName pulumi.StringInput `pulumi:"ruleSetName"`
	// A list of S3 Action blocks. Documented below.
	S3Actions pulumi.ArrayInput `pulumi:"s3Actions"`
	// If true, incoming emails will be scanned for spam and viruses
	ScanEnabled pulumi.BoolInput `pulumi:"scanEnabled"`
	// A list of SNS Action blocks. Documented below.
	SnsActions pulumi.ArrayInput `pulumi:"snsActions"`
	// A list of Stop Action blocks. Documented below.
	StopActions pulumi.ArrayInput `pulumi:"stopActions"`
	// Require or Optional
	TlsPolicy pulumi.StringInput `pulumi:"tlsPolicy"`
	// A list of WorkMail Action blocks. Documented below.
	WorkmailActions pulumi.ArrayInput `pulumi:"workmailActions"`
}

// The set of arguments for constructing a ReceiptRule resource.
type ReceiptRuleArgs struct {
	// A list of Add Header Action blocks. Documented below.
	AddHeaderActions pulumi.ArrayInput `pulumi:"addHeaderActions"`
	// The name of the rule to place this rule after
	After pulumi.StringInput `pulumi:"after"`
	// A list of Bounce Action blocks. Documented below.
	BounceActions pulumi.ArrayInput `pulumi:"bounceActions"`
	// If true, the rule will be enabled
	Enabled pulumi.BoolInput `pulumi:"enabled"`
	// A list of Lambda Action blocks. Documented below.
	LambdaActions pulumi.ArrayInput `pulumi:"lambdaActions"`
	// The name of the rule
	Name pulumi.StringInput `pulumi:"name"`
	// A list of email addresses
	Recipients pulumi.ArrayInput `pulumi:"recipients"`
	// The name of the rule set
	RuleSetName pulumi.StringInput `pulumi:"ruleSetName"`
	// A list of S3 Action blocks. Documented below.
	S3Actions pulumi.ArrayInput `pulumi:"s3Actions"`
	// If true, incoming emails will be scanned for spam and viruses
	ScanEnabled pulumi.BoolInput `pulumi:"scanEnabled"`
	// A list of SNS Action blocks. Documented below.
	SnsActions pulumi.ArrayInput `pulumi:"snsActions"`
	// A list of Stop Action blocks. Documented below.
	StopActions pulumi.ArrayInput `pulumi:"stopActions"`
	// Require or Optional
	TlsPolicy pulumi.StringInput `pulumi:"tlsPolicy"`
	// A list of WorkMail Action blocks. Documented below.
	WorkmailActions pulumi.ArrayInput `pulumi:"workmailActions"`
}
